Repository HI-dle/table-eat-now, pull requests merged in 2025-05, with the labels that each got.

#254 [restaurant] 컨슈머 concurrency 설정
  restaurant/src/main/java/table/eat/now/restaurant/restaurant/infrastructure/messaging/kafka/config/RestaurantKafkaConsumerConfig.java
  restaurant/src/main/resources/properties/kafka.yml
Labels: ✨ feat, ⚙️ setting

#255 [coupon/gateway] 빌드 실패로 인한 수정 및 재시도
  .github/workflows/ci-cd.yml
  coupon/docker-compose.yml
  gateway/src/main/java/table/eat/now/gateway/filter/JwtAuthenticationFilter.java
Labels: 🌎 deploy, ⚙️ setting, ✅ test

#260 [docs] readme 작성
  README.md
Labels: 📝 docs

#263 [common]ci/cd 워크플로우 수정
  .github/workflows/ci-cd.yml
Labels: 🌎 deploy, ♻️ refactor

#265 [coupon] 캐시 write back 디비 싱크 구현
  coupon/src/main/java/table/eat/now/coupon/coupon/application/scheduler/CouponScheduler.java
  coupon/src/main/java/table/eat/now/coupon/coupon/application/scheduler/config/SchedulingConfig.java
  coupon/src/main/java/table/eat/now/coupon/coupon/application/service/CouponServiceImpl.java
  coupon/src/main/java/table/eat/now/coupon/coupon/application/usecase/SyncCouponCacheToDbUsecase.java
  coupon/src/main/java/table/eat/now/coupon/coupon/domain/entity/Coupon.java
  coupon/src/main/java/table/eat/now/coupon/coupon/domain/reader/CouponReader.java
  coupon/src/main/java/table/eat/now/coupon/coupon/domain/store/CouponStore.java
  coupon/src/main/java/table/eat/now/coupon/coupon/infrastructure/persistence/CouponReaderImpl.java
  coupon/src/main/java/table/eat/now/coupon/coupon/infrastructure/persistence/CouponStoreImpl.java
  coupon/src/main/java/table/eat/now/coupon/coupon/infrastructure/persistence/jpa/JpaCouponRepository.java
  coupon/src/main/java/table/eat/now/coupon/coupon/infrastructure/persistence/redis/RedisCouponCacheManager.java
  coupon/src/main/java/table/eat/now/coupon/coupon/infrastructure/persistence/redis/config/CouponRedisConfig.java
  coupon/src/main/java/table/eat/now/coupon/coupon/infrastructure/persistence/redis/constant/CouponCacheConstant.java
  coupon/src/main/java/table/eat/now/coupon/global/metric/KafkaLagMetricProvider.java
  coupon/src/main/java/table/eat/now/coupon/global/scheduler/KafkaLagMeasureScheduler.java
  coupon/src/main/java/table/eat/now/coupon/global/scheduler/config/SchedulingConfig.java
  coupon/src/main/resources/redis/coupon/limited_nondup.lua
  coupon/src/main/resources/redis/coupon/limited_nondup_test.lua
  coupon/src/test/java/table/eat/now/coupon/coupon/application/scheduler/CouponSchedulerTest.java
  coupon/src/test/java/table/eat/now/coupon/coupon/application/service/CouponServiceImplTest.java
  coupon/src/test/java/table/eat/now/coupon/coupon/application/usecase/PrepareDailyCouponCacheUsecaseTest.java
  coupon/src/test/java/table/eat/now/coupon/coupon/application/usecase/SyncCouponCacheToDbUsecaseTest.java
  coupon/src/test/java/table/eat/now/coupon/coupon/fixture/CouponFixture.java
  coupon/src/test/java/table/eat/now/coupon/coupon/infrastructure/persistence/redis/RedisCouponIssueSpeedTest.java
  coupon/src/test/java/table/eat/now/coupon/helper/IntegrationTestSupport.java
  coupon/src/test/java/table/eat/now/coupon/testdata/CouponTestDataSaver.java
Labels: ✨ feat, ✅ test
